version: '3'
services:

  dbt:
    image: urykhy/dbt
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
