version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: clickhouse-zk
    hostname: zookeeper
    networks:
      clickhouse:
        aliases:
          - zk
    volumes:
      - clickhouse-zk1:/data
      - clickhouse-zk2:/datalog

  master:
    build: .
    image: urykhy/clickhouse
    container_name: clickhouse-master
    hostname: master
    networks:
      clickhouse:
        aliases:
          - master
    volumes:
      - clickhouse-master:/var/lib/clickhouse
    depends_on:
      - zookeeper

  shard1-a:
    build: .
    image: urykhy/clickhouse
    container_name: clickhouse-shard1-a
    hostname: shard1-a
    networks:
      clickhouse:
        aliases:
          - shard1-a
    volumes:
      - clickhouse-1a:/var/lib/clickhouse
    depends_on:
      - master
    environment:
      SHARD: 1

  shard1-b:
    build: .
    image: urykhy/clickhouse
    container_name: clickhouse-shard1-b
    hostname: shard1-b
    networks:
      clickhouse:
        aliases:
          - shard1-b
    volumes:
      - clickhouse-1b:/var/lib/clickhouse
    depends_on:
      - shard1-a
    environment:
      SHARD: 1

  shard2-a:
    build: .
    image: urykhy/clickhouse
    container_name: clickhouse-shard2-a
    hostname: shard2-a
    networks:
      clickhouse:
        aliases:
        - shard2-a
    volumes:
      - clickhouse-2a:/var/lib/clickhouse
    depends_on:
      - shard1-b
    environment:
      SHARD: 2

  shard2-b:
    build: .
    image: urykhy/clickhouse
    container_name: clickhouse-shard2-b
    hostname: shard2-b
    networks:
      clickhouse:
        aliases:
        - shard2-b
    volumes:
      - clickhouse-2b:/var/lib/clickhouse
    depends_on:
      - shard2-a
    environment:
      SHARD: 2

networks:
  clickhouse:
    external: true

volumes:
  clickhouse-master:
    external: true
  clickhouse-1a:
    external: true
  clickhouse-1b:
    external: true
  clickhouse-2a:
    external: true
  clickhouse-2b:
    external: true
  clickhouse-zk1:
    external: true
  clickhouse-zk2:
    external: true
