filebeat.registry.path: /usr/share/filebeat/data
filebeat.inputs:
- type: docker
  containers.ids: '*'
  processors:
  - add_docker_metadata: ~
- type: log
  paths:
  - /var/log/syslog
  - /var/log/apache2/virtual/*.log
  - /var/log/apache2/*.log
output.logstash:
  hosts: ["logstash.elk.docker:5044"]
logging.metrics.enabled: false
