filebeat.registry.path: /usr/share/filebeat/data
filebeat.inputs:
- type: docker
  containers.ids: '*'
  processors:
  - add_docker_metadata: ~
- type: log
  paths:
  - /var/log/syslog
output.logstash:
  hosts: ["logstash:5044"]
logging.metrics.enabled: false
