services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    volumes:
      - registry:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    network_mode: "bridge"
volumes:
  registry:
    external: true
