version: "0.5"
is_tui_disabled: true

processes:
  api:
    command: /usr/src/snuba/docker_entrypoint.sh api
    availability:
        restart: on_failure

  consumer:
    command: /usr/src/snuba/docker_entrypoint.sh consumer --storage errors --auto-offset-reset=latest --max-batch-time-ms 750
    availability:
        restart: on_failure

  outcomes:
    command: /usr/src/snuba/docker_entrypoint.sh consumer --storage outcomes_raw --auto-offset-reset=earliest --max-batch-time-ms 750
    availability:
        restart: on_failure

  sessions:
    command: /usr/src/snuba/docker_entrypoint.sh consumer --storage sessions_raw --auto-offset-reset=latest --max-batch-time-ms 750
    availability:
        restart: on_failure

  transactions:
    command: /usr/src/snuba/docker_entrypoint.sh consumer --storage transactions --auto-offset-reset=latest --max-batch-time-ms 750 --consumer-group transactions_group
    availability:
        restart: on_failure

  replacer:
    command: /usr/src/snuba/docker_entrypoint.sh replacer --storage errors --auto-offset-reset=latest
    availability:
        restart: on_failure

  s-events:
    command: /usr/src/snuba/docker_entrypoint.sh subscriptions-scheduler-executor --dataset events --entity events --auto-offset-reset=latest --no-strict-offset-reset --consumer-group=snuba-events-subscriptions-consumers --followed-consumer-group=snuba-consumers --delay-seconds=60 --schedule-ttl=60 --stale-threshold-seconds=900
    availability:
        restart: on_failure

  s-transactions:
    command: /usr/src/snuba/docker_entrypoint.sh subscriptions-scheduler-executor --dataset transactions --entity transactions --auto-offset-reset=latest --no-strict-offset-reset --consumer-group=snuba-transactions-subscriptions-consumers --followed-consumer-group=transactions_group --delay-seconds=60 --schedule-ttl=60 --stale-threshold-seconds=900
    availability:
        restart: on_failure