services:
  ospf:
    image: urykhy/ospf
    build:
      context: .
    hostname: ospf
    container_name: ospf
    network_mode: "host"
    privileged: true
    command: /usr/sbin/ospfd
    volumes:
    - ./quagga:/etc/quagga

  zebra:
    extends:
      service: ospf
    container_name: zebra
    hostname: zebra
    command: /usr/sbin/zebra
