---
server:
  address: "tcp://:9091"

log:
  level: "debug"

identity_validation:
  reset_password:
    jwt_secret: "tTYijMudhEQ9cw5PHasQieXPZXbwSv"

authentication_backend:
  file:
    path: "/config/users_database.yml"

access_control:
  default_policy: "one_factor"

session:
  secret: "9zrRDhdXG0jNLeDayGvpF9coXwaTdN"

  cookies:
    - name: "authelia_session"
      domain: "elf.dark" # Should match whatever your root protected domain is
      authelia_url: "https://authelia.elf.dark"
      expiration: "24 hour"
      inactivity: "5 minutes"

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  encryption_key: "kR3jsnYwD0OpyzqSRSnAVufGymnfMh1pxVOfGq0FFcOKHbaxvf6go3kHlwxx"
  local:
    path: "/config/db.sqlite3"

notifier:
  filesystem:
    filename: "/config/notification.txt"

identity_providers:
  oidc:
    jwks:
      - key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChEcdspc1SeMtE
          vMmZF9xy0wgxoiKHg7JY1o5VatApgBuWRWEL9jvn1iyU3XlMCxKg8zKl0+7e4XsQ
          ZUOe4zq0azhD/ALV4WDI76Gh9HUdkCicvgRXaUsqMLcJ6RMnx+bMXqoQqgISTcmf
          fI9e7hRmZB44lGAGOO/aBz4+/lqXuFPHFb/yaTF9kBnUKDU/cD5rU8RdLDe1Ew+3
          iMp2jysJJfPgx3UDwMAbBxECgdfio0SZVQo7Ilzr81aDw4iuhIRaFI705Vvxz1KT
          wT59rodxyr7wNjM+HcHmLXMyubMsXYwPR+k0jU6Yc83AKawxeeDmBI6WyCLlKWl9
          q8sAMDv3AgMBAAECggEAJedXrU81Sr+nYhUlQfQ2CgV0a62yf35z9WkEVMCOnP2L
          QGkyRczb2xpxIlUeKtF+QEcK97Awid25Bqo16AmkMnn64zDGgAuKKa8Os9yhxOO8
          Uup6fhGGwTZ2lIv3WIi33Qc38TT4yNLqbDA1Uwsm3NOZswnjsQMsGnxS3yMfMY2s
          riG1t3Y2HE5yG5Wf4innoavhyC3xnwwckjJ+2JtppefFgT97yeA1nyUMQZyqEmx1
          zBUDEVYR+yzrRgrjA1+lrGRJW5XoK2KDFXa46T4BJ+V8z1dvAuNHpgP1H082x6wh
          uXp7V7hLYvwmoD5OtNkFZCYDqBTI0D38RXwGFuqjUQKBgQDcsI6tXw19X2jYY2uO
          pORiIH+pCvjPKtnH25KRwfvnRUkYZZdbwWbtiaZ7Go2UPyQUdVujcq7zyRr92S9s
          K3/Mpguo0i1pKIiKq29OqTSs6cEjoXx+LfNDAoDAP+9s2SGpggXiW95j5vBc35CS
          Swh0e9bJXkwH0ZPmVPK2czTipwKBgQC61y3L86jDib94lQkMfh2UTxYDqpRAPua/
          dYcKM4NEaDyk4uhfjO5G3z/P7xfVRQW6hLeTPwydhvTBsIsUnVVr+BeCpqCdNGEb
          jQcxbAkjk9ZNu/5QW/YIlR4TuaRefs7fNqpHz+IqMFBDlIAezXllOXqAygbibnnT
          JHf8TwWWMQKBgEURoOXTzOYDGU43926iXrPzVeDzBSHZWGV7a+jgXFVqUtEm4nMe
          GXeYUBlRGyRdio44mKCUAPtdYmw2L+hbyNik0xtYBExYGjvEIcbtoAXJ9t+O5+aZ
          vPuo6eDBYc6gOi/R+MN6WyTLH0kB0z5l61SBeZx2PbdouTAqP/goIFIbAoGAVtmv
          cB7TVBGz71lX23bESSx6Dzo7r6GNoXIAU72eRy4tAnh3i/L2z/r2rrF1Yq2y/AC1
          VLz6ID+bhm2KOQrpqkaopxLNlkXC3guwTEjr9p3CAGBi1vfoZhTq5kBlJ4fKoffH
          L5pyhynuJXviEm9w/py5VSSUDq1L89n/7EjPUAECgYBfVn4TCUiB3L2LxzOit+OC
          iiEbfI8CJg8J8M/LtYJRpcRO1g+4qvzSpNKbVPguxFpn/5NLBi50u9wVVeUG7ZSx
          aFh4VMy8mnCoSGsmp23yiDFzZ59ICkhE2w78tV2vXKvgzuujsMk64UA/F5L/AB9p
          1LxS26Uy/ihrlEn3l54aOg==
          -----END PRIVATE KEY-----
    clients:
      - client_id: "photoprism"
        client_name: "photoprism"
        client_secret: "$pbkdf2-sha512$310000$XR72lU.92pU5LIQ2unu3FQ$.f4BcuXJjKdeSISheTPR.JWzbxf7F3xFTMhq94BsSPfnTxScg.qYfaZqH4UKRP8VztRuKjB/eOatR4EBCRQ2NA"
        public: false
        authorization_policy: "one_factor"
        require_pkce: false
        redirect_uris:
          - "https://photo.elf.dark/api/v1/oidc/redirect"
        scopes:
          - "email"
          - "openid"
          - "profile"
        response_types:
          - "code"
        grant_types:
          - "authorization_code"
        access_token_signed_response_alg: "none"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
