version: '2.1'

services:
    clickhouse:
      container_name: jaeger-clickhouse
      image: clickhouse/clickhouse-server:22.9
      networks:
        - jaeger
      volumes:
        - jaeger-clickhouse:/var/lib/clickhouse
        - ./clickhouse.xml:/etc/clickhouse-server/config.xml
      healthcheck:
        test: clickhouse-local -q 'select 1'
        interval: 1s
        timeout: 1s
        retries: 10

    collector:
      build: .
      image: urykhy/jaeger
      container_name: jaeger-collector
      command: jaeger-collector --collector.zipkin.host-port=:9411
      networks:
        jaeger:
      depends_on:
        clickhouse:
          condition: service_healthy

    agent:
      container_name: jaeger-agent
      image: urykhy/jaeger
      command: jaeger-agent --reporter.grpc.host-port=jaeger-collector.jaeger:14250
      networks:
        jaeger:
      depends_on:
        - collector

    query:
      container_name: jaeger-query
      image: urykhy/jaeger
      command: jaeger-query
      networks:
        jaeger:
      depends_on:
        - agent

networks:
  jaeger:
    external: true

volumes:
  jaeger-clickhouse:
    external: true
