version: '2'

services:
  swarm1:
    privileged: true
    image: docker:dind
    container_name: swarm1
    hostname: swarm1
    networks:
      - swarm
    volumes:
      - swarm1:/var/lib/docker
    command: dockerd --dns=10.103.10.3 --storage-driver=overlay2 --insecure-registry=registry:5000

  swarm2:
    privileged: true
    image: docker:dind
    container_name: swarm2
    hostname: swarm2
    networks:
      - swarm
    volumes:
      - swarm2:/var/lib/docker
    command: dockerd --dns=10.103.10.3 --storage-driver=overlay2 --insecure-registry=registry:5000
    depends_on:
      - swarm1

  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    networks:
      - swarm
    volumes:
      - registry:/var/lib/registry
    depends_on:
      - swarm2

networks:
  swarm:
    external: true

volumes:
  swarm1:
    external: true
  swarm2:
    external: true
  registry:
    external: true
