---
apiVersion: 1
datasources:
  - uid: fsezzmEnk
    type: prometheus
    name: Prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
