version: "2"

services:
  db:
    image: mysql:8.0.36-debian
    container_name: gitea-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - gitea_db:/var/lib/mysql

  server:
    image: gitea/gitea:1.21.6
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=100
      - GITEA__DATABASE__DB_TYPE=mysql
      - GITEA__DATABASE__HOST=db.gitea:3306
      - GITEA__DATABASE__USER=gitea
      - GITEA__DATABASE__PASSWD=gitea
      - GITEA__SERVER__HTTP_PORT=3000
      - GITEA__SERVER__SSH_DOMAIN=server.gitea.docker
      - GITEA__SERVER__ROOT_URL="http://server.gitea.docker:3000/"
      - GITEA__OAUTH2__JWT_SIGNING_ALGORITHM="HS256"
      - GITEA__REPOSITORY__DEFAULT_BRANCH=master
      - GITEA__ACTIONS__ENABLED=true
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    networks:
      - gitea
    volumes:
      - gitea_server:/data
    depends_on:
      - db

  runner:
    image: gitea/act_runner:nightly
    container_name: gitea-runner
    networks:
      - gitea
    volumes:
      - ./runner.yaml:/etc/runner.yaml
      - gitea_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_FILE=/etc/runner.yaml
      - GITEA_INSTANCE_URL=http://server.gitea.docker:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=yJwKNsf8qGxJZVDrV7OrLoYydcUEqV2HuaJ58Ut7
    depends_on:
      - server

  drone:
    image: drone/drone:2.22.0
    container_name: gitea-drone
    networks:
      - gitea
    volumes:
      - gitea_drone:/data
    environment:
      - DRONE_OPEN=true
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GITEA_SERVER=http://server.gitea.docker:3000/
      - DRONE_GITEA_CLIENT_ID=c7a66454-7333-4226-b95d-408fdfb1ed72
      - DRONE_GITEA_CLIENT_SECRET=hB04e7qInamIxf2Xk4fhjn19ckMG7uXYt5L1QaDT4zmI
      - DRONE_SERVER_HOST=drone.gitea.docker:80
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=123
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=drone:drone@tcp(db.gitea:3306)/drone?parseTime=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_USER_CREATE=username:urykhy,admin:true
      - DRONE_DATADOG_ENABLED=false
    depends_on:
      - server

  agent:
    image: drone/drone-runner-docker:1.8.3
    container_name: gitea-agent
    command: agent
    networks:
      - gitea
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone.gitea.docker
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=123
      - DRONE_LOGS_DEBUG=true

volumes:
  gitea_db:
    external: true
  gitea_server:
    external: true
  gitea_runner:
    external: true
  gitea_drone:
    external: true

networks:
  gitea:
    external: true
