version: "2"

services:
  db:
    image: mysql:5.7
    container_name: gitea-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - gitea_db:/var/lib/mysql

  server:
    image: gitea/gitea:latest
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=100
      - DB_TYPE=mysql
      - DB_HOST=db.gitea:3306
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - SSH_DOMAIN=server.gitea.docker
      - RUN_MODE=dev
      - ROOT_URL="http://server.gitea.docker:3000/"
      - GITEA__OAUTH2__JWT_SIGNING_ALGORITHM="HS256"
    networks:
      - gitea
    volumes:
      - gitea_server:/data
    depends_on:
      - db

  drone:
    image: drone/drone:latest
    container_name: gitea-drone
    networks:
      - gitea
    volumes:
      - gitea_drone:/var/lib/drone/
      - gitea_drone2:/data
    environment:
      - DRONE_OPEN=true
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GITEA_SERVER=http://server.gitea.docker:3000/
      - DRONE_GITEA_CLIENT_ID=c7a66454-7333-4226-b95d-408fdfb1ed72
      - DRONE_GITEA_CLIENT_SECRET=hB04e7qInamIxf2Xk4fhjn19ckMG7uXYt5L1QaDT4zmI
      - DRONE_SERVER_HOST=drone.gitea.docker:80
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=123
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=drone:drone@tcp(db.gitea:3306)/drone?parseTime=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_USER_CREATE=username:urykhy,admin:true
    depends_on:
      - server

  agent:
    image: drone/agent:latest
    container_name: gitea-agent
    command: agent
    networks:
      - gitea
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone.gitea.docker
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=123
      - DRONE_LOGS_DEBUG=true

volumes:
  gitea_db:
    external: true
  gitea_server:
    external: true
  gitea_drone:
    external: true
  gitea_drone2:
    external: true

networks:
  gitea:
    external: true
