services:
  postgres:
    image: postgres:15-alpine
    container_name: keycloak-postgres
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    network_mode: "bridge"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "keycloak-pg:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 1s
      timeout: 1s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak-server
    command: "start-dev"
    network_mode: "bridge"
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: "jdbc:postgresql://postgres.keycloak:5432/keycloak"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  keycloak-pg:
    external: true
