global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'email'
  routes:
  - receiver: 'oncall'
    continue: true
  - receiver: 'email'
    continue: true

receivers:
- name: 'email'
  email_configs:
  - to: 'alert@elf.dark'
    from: 'alert@elf.dark'
    smarthost: mail.dark:25
    require_tls: false
- name: 'oncall'
  webhook_configs:
  - url: 'http://oncall.grafana:8080/integrations/v1/alertmanager/E0F9IA5FfWdYkbVA5A759YfOh/'
    send_resolved: true
