version: '3.9'

include:
  - oncall-compose.yml
  - prometheus-compose.yml

services:
  grafana:
    image: grafana/grafana:11.2.0
    hostname: grafana
    container_name: grafana
    networks:
      - grafana
    volumes:
      - "grafana_data:/var/lib/grafana"

  tempo:
    image: grafana/tempo:latest
    hostname: tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - grafana
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"
      - "grafana_tempo:/data"
    #  ports
    #  80      # tempo api
    #  6831    # jaeger/thrift_compact on udp

  graphite:
    image: nickstenning/graphite
    hostname: graphite
    container_name: graphite
    networks:
      - grafana
    volumes:
      - "graphite:/var/lib/graphite/storage/whisper/"
    profiles: ["graphite"]

networks:
  grafana:
    external: true
volumes:
  graphite:
    external: true
  grafana_data:
    external: true
  grafana_tempo:
    external: true
