include:
  - oncall-compose.yml
  - prometheus-compose.yml

services:
  grafana:
    image: grafana/grafana:12.1.1
    hostname: grafana
    container_name: grafana-server
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - "grafana_data:/var/lib/grafana"

  pyroscope:
    image: grafana/pyroscope:latest
    hostname: pyroscope
    container_name: grafana-pyroscope
    networks:
      - grafana
    volumes:
      - "grafana-pyro-data:/data"
      - "grafana-pyro-comp:/data-compactor"
    # ports 4040
    profiles: ["grafana"]

  alloy:
    privileged: true
    user: root
    pid: host
    image: grafana/alloy:v1.7.4
    hostname: alloy
    container_name: grafana-alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    networks:
      - grafana
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    # ports 12345
    profiles: ["grafana"]

  tempo:
    image: grafana/tempo:latest
    hostname: tempo
    container_name: grafana-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - grafana
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"
      - "grafana_tempo:/data"
    profiles: ["grafana"]
    #  ports
    #  80      # tempo api
    #  6831    # jaeger/thrift_compact on udp

  graphite:
    image: nickstenning/graphite
    hostname: graphite
    container_name: grafana-graphite
    networks:
      - grafana
    volumes:
      - "graphite:/var/lib/graphite/storage/whisper/"
    profiles: ["graphite"]

networks:
  grafana:
    external: true
volumes:
  graphite:
    external: true
  grafana_data:
    external: true
  grafana_tempo:
    external: true
  grafana-pyro-data:
    external: true
  grafana-pyro-comp:
    external: true
