services:
  oncall:
    image: grafana/oncall:latest
    container_name: grafana-oncall-server
    command: bash -c "python manage.py migrate --noinput && exec uwsgi --ini uwsgi.ini"
    networks:
      - grafana
    env_file: oncall-env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    profiles: ["oncall"]

  celery:
    image: grafana/oncall:latest
    container_name: grafana-oncall-celery
    command: ./celery_with_exporter.sh
    networks:
      - grafana
    env_file: oncall-env
    depends_on:
      - oncall
    profiles: ["oncall"]

  redis:
    image: redis
    container_name: grafana-oncall-redis
    networks:
      - grafana
    volumes:
      - "grafana-oncall-redis:/data"
    profiles: ["oncall"]

  mysql:
    image: mysql:8.0-debian
    container_name: grafana-oncall-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log-error-verbosity=1
    networks:
      - grafana
    env_file: oncall-env
    volumes:
      - grafana-oncall-mysql:/var/lib/mysql
    healthcheck:
      test: mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -h127.0.0.1 -e 'select 1'
      timeout: 1s
      interval: 1s
      retries: 10
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    profiles: ["oncall"]

volumes:
  grafana-oncall-redis:
    external: true
  grafana-oncall-mysql:
    external: true
