services:
  prometheus:
    image: prom/prometheus:v2.47.2
    hostname: prometheus
    container_name: grafana-prometheus
    networks:
      - grafana
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules-slo.yml:/etc/prometheus/rules-slo.yml
      - ./rules-an.yml:/etc/prometheus/rules-an.yml
      - prometheus:/prometheus

  alertmanager:
    image: prom/alertmanager:v0.26.0
    hostname: alertmanager
    container_name: grafana-alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://alertmanager.grafana:9093"
    networks:
      - grafana
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager:/alertmanager

volumes:
  prometheus:
    external: true
  alertmanager:
    external: true
