version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    networks:
      - grafana
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - prometheus:/prometheus
    profiles: ["prometheus"]

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    networks:
      - grafana
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager:/alertmanager
    profiles: ["prometheus"]

volumes:
  prometheus:
    external: true
  alertmanager:
    external: true
