services:
  redis:
    image: redis:7.2-alpine
    hostname: nextcloud-redis
    container_name: nextcloud-redis
    network_mode: "bridge"
    volumes:
      - "nextcloud-redis:/data"

  mysql:
    image: mysql:8.0.36-debian
    hostname: nextcloud-mysql
    container_name: nextcloud-mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=0 --binlog-format=ROW --character-set-server=utf8mb4 --collation_server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
    network_mode: "bridge"
    volumes:
      - nextcloud-mysql:/var/lib/mysql

  nextcloud:
    cpus: 1
    image: urykhy/nextcloud
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
    hostname: nextcloud
    container_name: nextcloud
    network_mode: "bridge"
    volumes:
      - "nextcloud:/var/www/html"
    environment:
      REDIS_HOST: redis.nextcloud
    depends_on:
      - redis
      - mysql

  cron:
    image: urykhy/nextcloud
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
    hostname: nextcloud-cron
    container_name: nextcloud-cron
    network_mode: "bridge"
    user: www-data
    command: /bin/cron.sh
    stop_signal: INT
    volumes_from:
      - nextcloud
    environment:
      REDIS_HOST: redis.nextcloud
    depends_on:
      - redis
      - mysql
      - nextcloud

volumes:
  nextcloud:
    external: true
  nextcloud-redis:
    external: true
  nextcloud-mysql:
    external: true

