version: '2'
services:
  nextcloud:
    image: nextcloud:20
    hostname: nextcloud
    network_mode: "bridge"
    volumes:
      - "nextcloud:/var/www/html"

volumes:
  nextcloud:
    external: true
