version: '2'
services:
  nextcloud:
    image: nextcloud:26.0.0
    hostname: nextcloud
    container_name: nextcloud
    network_mode: "bridge"
    volumes:
      - "nextcloud:/var/www/html"

  cron:
    image: nextcloud:25.0.0
    hostname: nextcloud-cron
    container_name: nextcloud-cron
    network_mode: "bridge"
    user: www-data
    command: /bin/cron.sh
    stop_signal: INT
    volumes_from:
      - nextcloud
    volumes:
      - ./cron.sh:/bin/cron.sh

volumes:
  nextcloud:
    external: true
