version: '2'
services:
  redis:
    image: redis:7.2-alpine
    hostname: nextcloud-redis
    container_name: nextcloud-redis
    network_mode: "bridge"
    volumes:
      - "nextcloud-redis:/data"

  nextcloud:
    cpus: 1
    image: urykhy/nextcloud
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
    hostname: nextcloud
    container_name: nextcloud
    network_mode: "bridge"
    volumes:
      - "nextcloud:/var/www/html"
    environment:
      REDIS_HOST: redis.nextcloud
    depends_on:
      - redis

  cron:
    image: urykhy/nextcloud
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
    hostname: nextcloud-cron
    container_name: nextcloud-cron
    network_mode: "bridge"
    user: www-data
    command: /bin/cron.sh
    stop_signal: INT
    volumes_from:
      - nextcloud
    environment:
      REDIS_HOST: redis.nextcloud
    depends_on:
      - redis


volumes:
  nextcloud:
    external: true
  nextcloud-redis:
    external: true
