api: kube-apiserver --secure-port=443 --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=172.16.9.0/24 --service-account-key-file=/client.pub --tls-cert-file=/server.crt --tls-private-key-file=/server.key --kubelet-client-certificate=/client.crt --kubelet-client-key=/client.key --client-ca-file=/kube.ca --requestheader-allowed-names="" --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --requestheader-client-ca-file=/kube.ca --enable-aggregator-routing --allow-privileged=true
controller: kube-controller-manager --master=http://127.0.0.1:8080 --service-account-private-key-file=/client.key --root-ca-file=/kube.ca --allocate-node-cidrs --cluster-cidr=172.17.0.0/16
scheduler: kube-scheduler --master=http://127.0.0.1:8080
proxy: kube-proxy --kubeconfig=/kubeconfig --v=2 --conntrack-max-per-core=0
flanneld: flanneld --etcd-endpoints=http://172.16.9.2:2379
