version: '2.3'
services:
  jupyter:
    build:
      context: .
      args:
        APT_PROXY: http://elf.dark:8081
        S_PROXY: http://elf.dark:8082
        PIP_INDEX_URL: http://elf.dark:8080/simple
        PIP_TRUSTED_HOST: elf.dark
    image: urykhy/jupyter
    hostname: jupyter
    container_name: jupyter
    network_mode: "bridge"
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --no-browser .
    volumes:
      - "jupyter:/work"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
    privileged: true

volumes:
  jupyter:
    external: true
