volumes:
  sentry-postgres:
    external: true
  sentry-files:
    external: true
  sentry-redis:
    external: true
  sentry-clickhouse:
    external: true

networks:
  sentry:
    external: true

services:
  memcache:
    image: memcached:1.6.18-alpine
    container_name: sentry-memcache
    networks:
    - sentry

  redis:
    image: redis
    container_name: sentry-redis
    volumes:
    - sentry-redis:/data
    networks:
    - sentry

  postgres:
    image: postgres:17.4-alpine
    container_name: sentry-postgres
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
    - sentry-postgres:/var/lib/postgresql/data
    networks:
    - sentry

  clickhouse:
    image: clickhouse/clickhouse-server:22.9
    container_name: sentry-clickhouse
    volumes:
      - sentry-clickhouse:/var/lib/clickhouse
      - ./clickhouse.xml:/etc/clickhouse-server/config.xml
    networks:
      - sentry
    healthcheck:
      test: clickhouse-local -q 'select 1'
      interval: 1s
      timeout: 1s
      retries: 10

  snuba:
    image: urykhy/sentry-snuba
    command: process-compose up -f /process-compose.yaml
    build:
      context: snuba
      args:
        GOPROXY: ${GOPROXY}
    container_name: sentry-snuba
    networks:
      - sentry
    depends_on:
    - clickhouse
    env_file: .snuba-env

  web:
    depends_on:
    - memcache
    - redis
    - postgres
    - snuba
    image: getsentry/sentry:23.1.1
    container_name: sentry-web
    command: "sentry run web -w 2"
    networks:
    - sentry
    volumes:
    - sentry-files:/data
    - ./sentry.conf.py:/etc/sentry/sentry.conf.py
    env_file: .sentry-env
    user: sentry

  worker:
    extends:
      service: web
    image: urykhy/sentry-worker
    command: process-compose up -f /process-compose.yaml
    build:
      context: worker
      args:
        GOPROXY: ${GOPROXY}
    container_name: sentry-worker
    depends_on:
      - web
    user: sentry

  relay:
    image: getsentry/relay:23.1.1
    container_name: sentry-relay
    command: run -c /etc/relay
    networks:
    - sentry
    volumes:
    - sentry-files:/work
    - sentry-files:/etc/relay
    - ./relay.yml:/etc/relay/config.yml
    - ./credentials.json:/etc/relay/credentials.json
    - ./relay-projects:/etc/relay/projects
    depends_on:
    - worker
