version: '2'

volumes:
  sentry-db:
    external: true
  sentry-files:
    external: true
  sentry-redis:
    external: true

networks:
  sentry:
    external: true

services:
  redis:
    image: redis
    container_name: sentry-redis
    volumes:
    - sentry-redis:/data
    networks:
    - sentry

  postgres:
    image: postgres:12
    container_name: sentry-postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
    - sentry-db:/var/lib/postgresql/data
    networks:
    - sentry

  web:
    depends_on:
    - redis
    - postgres
    image: sentry:9.1.2
    container_name: sentry-web
    command: "sentry run web -w 2"
    networks:
    - sentry
    volumes:
    - sentry-files:/var/lib/sentry/files
    env_file: .env

  cron:
    depends_on:
    - redis
    - postgres
    image: sentry:9.1.2
    container_name: sentry-cron
    command: "sentry run cron"
    networks:
    - sentry
    volumes:
    - sentry-files:/var/lib/sentry/files
    env_file: .env

  worker:
    depends_on:
    - redis
    - postgres
    image: sentry:9.1.2
    container_name: sentry-worker
    command: "sentry run worker -c 2"
    networks:
    - sentry
    volumes:
    - sentry-files:/var/lib/sentry/files
    env_file: .env
