---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: default
data:
  k8s: |
    [k8s]
    type = http
    url = http://elf.dark
---
apiVersion: v1
kind: Pod
metadata:
  name: mount-with-rclone
  labels:
    application: mount-with-rclone
spec:
  volumes:
  - name: data
    emptyDir: {}
  - name: rclone-config
    configMap:
      name: rclone-config

  containers:
  - name: app
    image: alpine
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "tail -f /dev/null"
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: HostToContainer

  - name: rclone
    image: rclone/rclone:latest
    args:
      - "mount"
      - "k8s:"
      - "/data"
      - "--allow-non-empty"
      - "--allow-other"
      - "--config=/etc/rclone/k8s"
      - "--rc"
      - "--rc-enable-metrics"
      - "--rc-addr=0.0.0.0:5572"
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: Bidirectional
    - name: rclone-config
      mountPath: /etc/rclone
    lifecycle:
      preStop:
        exec:
          command: ["/bin/fusermount","-uz","/data"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: mount-with-rclone-metrics
  labels:
    application: mount-with-rclone
spec:
  selector:
    application: mount-with-rclone
  ports:
  - name: metrics
    port: 5572
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: prometheus
  name: mount-with-rclone-monitor
  labels:
    application: mount-with-rclone
spec:
  jobLabel: mount-with-rclone
  selector:
    matchLabels:
      application: mount-with-rclone
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 30s
