---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: default
data:
  k8s: |
    [k8s]
    type = http
    url = http://elf.dark
---
apiVersion: v1
kind: Pod
metadata:
  name: mount-with-rclone
spec:
  volumes:
  - name: data
    emptyDir: {}
  - name: rclone-config
    configMap:
      name: rclone-config

  containers:
  - name: app
    image: alpine
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "tail -f /dev/null"
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: HostToContainer

  - name: rclone
    image: quay.io/chaosaffe/rclone:latest
    args:
      - "mount"
      - "k8s:"
      - "/data"
      - "--allow-other"
      - "--config=/etc/rclone/k8s"
      - "--rc"
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: Bidirectional
    - name: rclone-config
      mountPath: /etc/rclone
    lifecycle:
      preStop:
        exec:
          command: ["/bin/fusermount","-uz","/data"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN