services:
  kerberos:
    image: urykhy/kerberos
    hostname: kerberos
    container_name: kerberos
    build:
      context: .
    network_mode: "host"
    privileged: true
    volumes:
      - "kerberos:/var/lib/krb5kdc"

  kadmin:
    extends:
      service: kerberos
    container_name: kadmin
    hostname: kadmin
    entrypoint: /usr/sbin/kadmind -P /var/run/kadmind.pid -nofork

volumes:
  kerberos:
    external: true
