services:
  jupyter:
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
        S_PROXY: ${S_PROXY}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
    image: urykhy/jupyter-spark
    hostname: jupyter-spark
    container_name: jupyter-spark
    network_mode: "bridge"
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' .
    volumes:
      - "jupyter:/work"

volumes:
  jupyter:
    external: true
