version: '2'
services:
  jenkins:
    image: jenkinsci/blueocean
    hostname: jenkins
    container_name: jenkins
    network_mode: "bridge"
    volumes:
      - "jenkins:/var/jenkins_home"
    environment:
      JAVA_OPTS: "-XX:+UseShenandoahGC -Xms64m -Xmx256m"

volumes:
  jenkins:
    external: true
