services:
  jenkins:
    image: urykhy/jenkins
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
    hostname: jenkins
    domainname: docker
    container_name: jenkins
    network_mode: "bridge"
    volumes:
      - "jenkins:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-XX:+UseShenandoahGC -Xms64m -Xmx512m"

volumes:
  jenkins:
    external: true
