version: '2.2'

services:
  server:
    hostname: elasticsearch
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    cpus: 2
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
      indices.memory.index_buffer_size: "60%"
      http.cors.allow-origin: "\"*\""
      http.cors.enabled: "true"
      xpack.security.enabled: "false"
      xpack.ml.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      discovery.type: "single-node"
    networks:
      - elk
    volumes:
     - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: >
        test `curl -s localhost:9200/_cluster/health?pretty | grep status | cut -d\" -f4` = "green"
      interval: 5s
      timeout: 5s
      retries: 10

  logstash:
    hostname: logstash
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.9.3
    cpus: 2
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash:/etc/logstash/conf.d
    networks:
      - elk
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: >
        test `curl -s localhost:9600/?pretty | grep status | cut -d\" -f4` = "green"
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx2g"

  kibana:
    hostname: kibana
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    cpus: 2
    networks:
      - elk
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: >
        curl -s localhost:5601/api/status
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      SERVER_NAME: "kibana"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      LOGGING_QUIET: "true"

  filebeat:
    user: root
    hostname: filebeat
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.9.3
    cpus: 1
    networks:
      - elk
    depends_on:
      logstash:
        condition: service_healthy
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log:/var/log:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - filebeat:/usr/share/filebeat/data/
    command: "filebeat -e -strict.perms=false"

networks:
  elk:
    external: true
volumes:
  elasticsearch:
    external: true
  filebeat:
    external: true
