version: '3'
services:
  email:
    image: urykhy/email
    build: email
    container_name: email
    hostname: elf.dark
    volumes:
     - /etc/passwd:/etc/passwd
     - /etc/group:/etc/group
     - /etc/shadow:/etc/shadow
     - /etc/exim4:/etc/exim4
     - /etc/dovecot:/etc/dovecot
     - /etc/aliases:/etc/aliases
     - /var/mail:/var/mail
     - /var/spool/mail:/var/spool/mail
     - /var/spool/exim4:/var/spool/exim4
     - /etc/ssl:/etc/ssl
    network_mode: "host"
    environment:
      PYTHONUNBUFFERED: 1

  samba:
    image: urykhy/samba
    build: samba
    container_name: samba
    volumes:
     - /etc/passwd:/etc/passwd
     - /etc/shadow:/etc/shadow
     - /etc/samba:/etc/samba
     - /etc/pure-ftpd:/etc/pure-ftpd
     - /home:/home
     - /u01:/u01
     - /u02:/u02
     - /u03:/u03
     - /var/lib/samba:/var/lib/samba
    network_mode: "host"
    privileged: true
    environment:
      PYTHONUNBUFFERED: 1

  apache:
    image: urykhy/apache
    build: apache
    container_name: apache
    volumes:
     - /etc/apache2:/etc/apache2
     - /etc/ssl:/etc/ssl
     - /home/ury:/home/ury
     - /var/www:/var/www
    network_mode: "host"
    environment:
      PYTHONUNBUFFERED: 1
