version: '3'

services:
  gns3:
    image: urykhy/gns3
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
    hostname: gns3
    container_name: gns3
    network_mode: "host"
    privileged: true
    environment:
      LIBGL_ALWAYS_INDIRECT: 1
      DISPLAY: ${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/machine-id:/etc/machine-id
    - gns3:/home/user/GNS3

volumes:
  gns3:
    external: true