version: '2'

services:
  debezium:
    image: debezium/server:2.3
    hostname: debezium
    container_name: debezium
    network_mode: "bridge"
    volumes:
      - ./conf:/debezium/conf
      - ./data:/debezium/data