name: coroot

volumes:
  prometheus: {}
  coroot: {}
  clickhouse: {}
  node-agent: {}

networks:
  coroot:
    external: true

services:
  coroot:
    image: ghcr.io/coroot/coroot:1.10.3
    volumes:
      - coroot:/data
    networks:
      - coroot
    command:
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=15s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
      - '--disable-usage-statistics'
      - '--data-dir=/data'
    depends_on:
      - clickhouse
      - prometheus

  node-agent:
    image: ghcr.io/coroot/coroot-node-agent:1.23.19
    privileged: true
    networks:
      - coroot
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - node-agent:/data
    command:
      - '--collector-endpoint=http://coroot:8080'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'

  prometheus:
    image: prom/prometheus:v2.45.4
    volumes:
      - prometheus:/prometheus
    networks:
      - coroot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - coroot
    volumes:
      - clickhouse:/var/lib/clickhouse/
      - ./default-user.xml:/etc/clickhouse-server/users.d/default-user.xml

  collector:
    image: otel/opentelemetry-collector:0.101.0
    networks:
      - coroot
    command: --config=/etc/otel.yaml
    volumes:
    - ./otel.yaml:/etc/otel.yaml
