services:
  node1:
    image: minio/minio
    env_file: env
    command: server http://node1/data http://node2/data http://node3/data http://node4/data
    networks:
      - minio
  node2:
    image: minio/minio
    env_file: env
    command: server http://node1/data http://node2/data http://node3/data http://node4/data
    networks:
      - minio
  node3:
    image: minio/minio
    env_file: env
    command: server http://node1/data http://node2/data http://node3/data http://node4/data
    networks:
      - minio
  node4:
    image: minio/minio
    env_file: env
    command: server http://node1/data http://node2/data http://node3/data http://node4/data
    networks:
      - minio

networks:
  minio:
    external: true
