version: '2'
services:
  node1:
    image: cassandra:3.11
    container_name: cassandra1
    environment:
      CASSANDRA_SEED: "cassandra1"
      JVM_OPTS: "-Xms128m -Xmx1g"
    networks:
      - cassandra
    volumes:
      - "cassandra1:/var/lib/cassandra"
  node2:
    image: cassandra:3.11
    container_name: cassandra2
    environment:
      CASSANDRA_SEEDS: "cassandra1"
      JVM_OPTS: "-Xms128m -Xmx1g"
    depends_on:
      - node1
    networks:
      - cassandra
    volumes:
      - "cassandra2:/var/lib/cassandra"

volumes:
  cassandra1:
    external: true
  cassandra2:
    external: true
networks:
  cassandra:
    external: true
