version: '3'
services:
  zookeeper:
    image: urykhy/zookeeper
    container_name: kafka-zk
    hostname: zookeeper
    networks:
      kafka:
    volumes:
      - kafka-zk:/data

  broker-1:
    image: urykhy/kafka
    build:
      context: .
      args:
        APT_PROXY: http://elf.dark:8081
    container_name: kafka-broker1
    hostname: broker-1
    domainname: kafka
    networks:
      kafka:
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/data
    environment:
      KAFKA_OPTS: -javaagent:/opt/jmx_prometheus_javaagent.jar=7071:/exporter.yml
      KAFKA_HEAP_OPTS: "-Xms64m -Xmx256m"
      KAFKA_JVM_PERFORMANCE_OPTS: -XX:+UseShenandoahGC
      KAFKA_BROKER_ID: 1
    expose:
      - "7071"
      - "9092"

  broker-2:
    extends:
      service: broker-1
    container_name: kafka-broker2
    hostname: broker-2
    depends_on:
      - broker-1
    environment:
      KAFKA_BROKER_ID: 2

  broker-3:
    extends:
      service: broker-1
    container_name: kafka-broker3
    hostname: broker-3
    depends_on:
      - broker-2
    environment:
      KAFKA_BROKER_ID: 3

volumes:
  kafka-zk:
    external: true
  kafka-data:
    external: true
networks:
  kafka:
    external: true
