services:
  zookeeper:
    image: urykhy/zookeeper
    container_name: kafka-zk
    hostname: zookeeper
    networks:
      kafka:
    volumes:
      - kafka-zk:/data

  broker-1:
    image: urykhy/kafka
    build:
      context: .
      args:
        APT_PROXY: ${APT_PROXY}
        S_PROXY: ${S_PROXY}
    container_name: kafka-broker1
    hostname: broker-1
    domainname: kafka
    networks:
      kafka:
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/data
    environment:
      KAFKA_OPTS: -javaagent:/opt/jmx_prometheus_javaagent.jar=7071:/exporter.yml
      KAFKA_HEAP_OPTS: "-Xms64m -Xmx256m"
      KAFKA_JVM_PERFORMANCE_OPTS: -XX:+UseShenandoahGC
      KAFKA_BROKER_ID: 1
    expose:
      - "7071"
      - "9092"

  broker-2:
    extends:
      service: broker-1
    container_name: kafka-broker2
    hostname: broker-2
    depends_on:
      - broker-1
    environment:
      KAFKA_BROKER_ID: 2

  broker-3:
    extends:
      service: broker-1
    container_name: kafka-broker3
    hostname: broker-3
    depends_on:
      - broker-2
    environment:
      KAFKA_BROKER_ID: 3

  ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    hostname: ui
    domainname: kafka
    networks:
      kafka:
    depends_on:
      - broker-3
    environment:
      JAVA_OPTS: -Xms64m -Xmx256m -XX:+UseShenandoahGC
      KAFKA_CLUSTERS_0_NAME: docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://registry:8081
      KAFKA_CLUSTERS_0_METRICS_TYPE: PROMETHEUS
      KAFKA_CLUSTERS_0_METRICS_PORT: 7071

  registry:
    image: confluentinc/cp-schema-registry:7.2.15
    container_name: kafka-registry
    hostname: kafka-registry
    networks:
      kafka:
    depends_on:
      - broker-3
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: -Xms64m -Xmx256m
      SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS: -XX:+UseShenandoahGC
      SCHEMA_REGISTRY_HOST_NAME: kafka-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://registry.kafka.docker:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:9092
      SCHEMA_REGISTRY_DEBUG: 'true'
    volumes:
      - kafka-registry:/etc/schema-registry/secrets

volumes:
  kafka-zk:
    external: true
  kafka-data:
    external: true
  kafka-registry:
    external: true
networks:
  kafka:
    external: true
