version: '3.9'
services:
  jekyll:
    image: urykhy/jekyll
    build: jekyll
    container_name: jekyll
    network_mode: "bridge"
    command: bash -c "bundler install && jekyll serve --trace --verbose --port 80 --host 0.0.0.0"
    volumes:
    - /home/ury/devel/jekyll/stuff:/srv/jekyll

  uwsgi-php:
    image: urykhy/uwsgi
    build: uwsgi
    container_name: uwsgi-php
    volumes:
    - /home/ury:/home/ury
    command: uwsgi php.ini
    network_mode: "bridge"

  uwsgi-torrent:
    image: urykhy/uwsgi
    build:
      context: uwsgi
      args:
        APT_PROXY: ${APT_PROXY}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
    container_name: uwsgi-torrent
    volumes:
    - /home/ury:/home/ury
    command: uwsgi torrent.ini
    network_mode: "bridge"
    environment:
      PYTHONUNBUFFERED: 1

  uwsgi-flibusta:
    image: urykhy/uwsgi
    build:
      context: uwsgi
      args:
        APT_PROXY: ${APT_PROXY}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
    container_name: uwsgi-flibusta
    volumes:
    - /home/ury:/home/ury
    - /u03/mirror/fb2.Flibusta.Net:/u03/mirror/fb2.Flibusta.Net
    command: uwsgi flibusta.ini
    network_mode: "bridge"
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql-master
      MYSQL_USER: user
      MYSQL_PASS: ""

  nginx:
    image: nginx:1.25.5-alpine-otel
    hostname: nginx
    container_name: nginx
    network_mode: "host"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/nginx.js:/etc/nginx/nginx.js
    - /home/ury:/home/ury
    - /etc/ssl/elf:/etc/ssl/elf
    - nginx-cache:/cache
    depends_on:
    - jekyll
    - uwsgi-php
    - uwsgi-torrent
    - uwsgi-flibusta
    restart: unless-stopped

  goproxy:
    image: goproxy/goproxy:latest
    command: "-listen=0.0.0.0:8080 -cacheDir=/go -proxy=https://goproxy.io/"
    hostname: goproxy
    container_name: goproxy
    network_mode: "bridge"
    volumes:
    - goproxy:/go

volumes:
  nginx-cache:
    external: true
  goproxy:
    external: true
