name: fdb

services:
  coordinator:
    image: foundationdb/foundationdb:7.3.43
    hostname: fdb-coordinator
    network_mode: "bridge"
    privileged: true
    environment:
      FDB_COORDINATOR: coordinator.fdb.docker
      FDB_CLUSTER_FILE: /etc/foundationdb/fdb.cluster
    init: true
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - "data:/var/fdb/data"
      - "logs:/var/fdb/logs"
      - "config:/etc/foundationdb"
      - "./foundationdb.conf.in:/tmp/foundationdb.conf.in"
      - "./fdb.cluster.in:/tmp/fdb.cluster.in"
      - "./entrypoint.sh:/entrypoint.sh"

  exporter:
    image: aikoven/foundationdb-exporter:3.0.0
    network_mode: "bridge"
    environment:
      FDB_CLUSTER_FILE: /etc/foundationdb/fdb.cluster
    volumes:
      - "config:/etc/foundationdb/"
    depends_on:
      - coordinator

volumes:
  data:
  logs:
  config:
