name: fdb

services:
  coordinator:
    image: foundationdb/foundationdb:7.3.43
    hostname: coordinator
    network_mode: "bridge"
    environment:
      FDB_COORDINATOR: coordinator.fdb.docker
      FDB_PROCESS_CLASS: coordinator
    volumes:
      - "coordinator:/var/fdb/data"

  server-stateless:
    image: foundationdb/foundationdb:7.3.43
    hostname: server-stateless
    network_mode: "bridge"
    environment:
      FDB_COORDINATOR: coordinator.fdb.docker
      FDB_PROCESS_CLASS: stateless
    depends_on:
      - coordinator
    volumes:
      - "server-stateless:/var/fdb/data"

  server-log:
    image: foundationdb/foundationdb:7.3.43
    hostname: server-log
    network_mode: "bridge"
    environment:
      FDB_COORDINATOR: coordinator.fdb.docker
      FDB_PROCESS_CLASS: log
    depends_on:
      - coordinator
    volumes:
      - "server-log:/var/fdb/data"

  server-storage:
    image: foundationdb/foundationdb:7.3.43
    hostname: server-storage
    network_mode: "bridge"
    environment:
      FDB_COORDINATOR: coordinator.fdb.docker
      FDB_PROCESS_CLASS: storage
    depends_on:
      - coordinator
    volumes:
      - "server-storage:/var/fdb/data"

volumes:
  coordinator:
  server-stateless:
  server-log:
  server-storage:
