version: '2'
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    hostname: ansible-semaphore
    container_name: ansible-semaphore
    network_mode: "bridge"
    volumes:
      - "semaphore:/var/lib/semaphore"
      - "/etc/ansible:/data/ansible"
      - "/home/ury/code/ansible-roles:/data/roles"
      - "/etc/ssl/elf:/etc/ssl/elf"
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
volumes:
  semaphore:
    external: true
